# Generated by Django 4.2.4 on 2023-10-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paramettre", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comzones",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="comzones",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="fichevisites",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="fichevisites",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="fichexpminieres",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="formguidautorites",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="formguidautorites",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="rapactivites",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="rapactivites",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="accidents",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="accidents",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="burencadrements",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="burencadrements",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartartisants",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartartisants",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="categories",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="categories",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="communes",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="communes",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="comptoires",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="comptoires",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="comsites",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="comsites",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="demandeconventions",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="demandeconventions",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="fichenrolements",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="fichenrolements",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="ficheprelevements",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="ficheprelevements",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="fichexpminieres",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="formdsracs",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="formdsracs",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="formincidents",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="formincidents",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="incidents",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="incidents",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="rapaccidents",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="rapaccidents",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="regions",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="regions",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="statutsites",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="statutsites",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typaccidents",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typaccidents",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typautorisations",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typautorisations",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typdemandeurs",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typdemandeurs",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typenatureminerais",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typenatureminerais",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typenatureterrains",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typenatureterrains",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typeorganisations",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typeorganisations",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typeproduitchimiques",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typeproduitchimiques",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typequipements",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typequipements",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typesites",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typesites",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typetaterrains",
            name="created",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="typetaterrains",
            name="modified",
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
