# Generated by Django 4.2.4 on 2023-11-01 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rapaccidents',
        ),
        migrations.RemoveField(
            model_name='formincidents',
            name='code_incident',
        ),
        migrations.RemoveField(
            model_name='formincidents',
            name='com_province',
        ),
        migrations.RemoveField(
            model_name='formincidents',
            name='com_region',
        ),
        migrations.RemoveField(
            model_name='formincidents',
            name='type_nature_incident',
        ),
        migrations.AddField(
            model_name='formincidents',
            name='action_corrective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formincidents',
            name='cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formincidents',
            name='degres',
            field=models.CharField(blank=True, choices=[('faible', 'FAIBLE'), ('moyen', 'MOYEN'), ('grave', 'GRAVE'), ('tres_grave', 'TRES GRAVE')], default='MOYEN', max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='formincidents',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formincidents',
            name='heure_incident',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formincidents',
            name='implication',
            field=models.CharField(blank=True, choices=[('exploitants', 'exploitants'), ('fournisseur', 'fournisseur'), ('commercants', 'commercants'), ('collecteurs', 'collecteurs'), ('visiteurs', 'visiteurs')], default='MOYEN', max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='formincidents',
            name='lieu',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='formincidents',
            name='mesure_de_securite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formincidents',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.provinces'),
        ),
        migrations.AddField(
            model_name='formincidents',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.regions'),
        ),
        migrations.AddField(
            model_name='formincidents',
            name='type',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Type accident ou incident'),
        ),
        migrations.AddField(
            model_name='formincidents',
            name='type_rapport',
            field=models.CharField(blank=True, choices=[('accident', 'ACCIDENT'), ('incident', 'INCIDENT')], default='exploitants', max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='formincidents',
            name='zone',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='formincidents',
            name='commune',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='formincidents',
            name='mort_enf',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de Mort Enfant'),
        ),
        migrations.AlterField(
            model_name='formincidents',
            name='mort_fem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de Mort Femme'),
        ),
        migrations.AlterField(
            model_name='formincidents',
            name='mort_hom',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de Mort Homme'),
        ),
        migrations.AlterField(
            model_name='formincidents',
            name='vict_enf',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre Victime Enfant'),
        ),
        migrations.AlterField(
            model_name='formincidents',
            name='vict_fem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre Victime Femme'),
        ),
        migrations.AlterField(
            model_name='formincidents',
            name='vict_hom',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre Victime Homme'),
        ),
    ]
