# Generated by Django 4.2.4 on 2023-11-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communes',
            old_name='province_id',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='provinces',
            old_name='region_id',
            new_name='region',
        ),
    ]
