# Generated by Django 4.2.4 on 2023-11-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created',
        ),
        migrations.RemoveField(
            model_name='message',
            name='modified',
        ),
    ]
