# Generated by Django 4.2.4 on 2023-10-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paramettre", "0002_comzones_created_comzones_modified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Typecarte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    models.DateField(auto_created=True, auto_now_add=True, null=True),
                ),
                (
                    "created",
                    models.DateField(auto_created=True, auto_now_add=True, null=True),
                ),
                ("libelle", models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                "verbose_name": "Typecarte",
                "verbose_name_plural": "Type de carte",
            },
        ),
        migrations.AlterModelOptions(
            name="accidents",
            options={"verbose_name": "Accidents", "verbose_name_plural": "Accident "},
        ),
        migrations.AlterModelOptions(
            name="burencadrements",
            options={
                "verbose_name": "Burencadrements",
                "verbose_name_plural": "Bureau d'encadrement",
            },
        ),
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "Categories", "verbose_name_plural": "Categorie"},
        ),
        migrations.AlterModelOptions(
            name="communes",
            options={"verbose_name": "Communes", "verbose_name_plural": "Commune"},
        ),
        migrations.AlterModelOptions(
            name="comptoires",
            options={"verbose_name": "Comptoires", "verbose_name_plural": "Comptoire"},
        ),
        migrations.AlterModelOptions(
            name="comsites",
            options={"verbose_name": "Comsites", "verbose_name_plural": "Site"},
        ),
        migrations.AlterModelOptions(
            name="comzones",
            options={"verbose_name": "Comzones", "verbose_name_plural": "Zone"},
        ),
        migrations.AlterModelOptions(
            name="incidents",
            options={"verbose_name": "Incidents", "verbose_name_plural": "Incident"},
        ),
        migrations.AlterModelOptions(
            name="provinces",
            options={"verbose_name": "Provinces", "verbose_name_plural": "Province"},
        ),
        migrations.AlterModelOptions(
            name="regions",
            options={"verbose_name": "Regions", "verbose_name_plural": "Region"},
        ),
        migrations.AlterModelOptions(
            name="statutsites",
            options={
                "verbose_name": "Statutsites",
                "verbose_name_plural": "Statutsite",
            },
        ),
        migrations.AlterModelOptions(
            name="typaccidents",
            options={
                "verbose_name": "Typaccidents",
                "verbose_name_plural": "Type d'accident",
            },
        ),
        migrations.AlterModelOptions(
            name="typautorisations",
            options={
                "verbose_name": "Typautorisations",
                "verbose_name_plural": "Type d'autorisation",
            },
        ),
        migrations.AlterModelOptions(
            name="typdemandeurs",
            options={
                "verbose_name": "Typdemandeurs",
                "verbose_name_plural": "Type demandeur",
            },
        ),
        migrations.AlterModelOptions(
            name="typenatureminerais",
            options={
                "verbose_name": "Typenatureminerais",
                "verbose_name_plural": "Nature du minerai",
            },
        ),
        migrations.AlterModelOptions(
            name="typenatureterrains",
            options={
                "verbose_name": "Typenatureterrains",
                "verbose_name_plural": "Nature terrain",
            },
        ),
        migrations.AlterModelOptions(
            name="typeorganisations",
            options={
                "verbose_name": "Typeorganisations",
                "verbose_name_plural": "Type d'organisation",
            },
        ),
        migrations.AlterModelOptions(
            name="typeproduitchimiques",
            options={
                "verbose_name": "Typeproduitchimiques",
                "verbose_name_plural": "Type de produit chimique",
            },
        ),
        migrations.AlterModelOptions(
            name="typequipements",
            options={
                "verbose_name": "Typequipements",
                "verbose_name_plural": "Type d'equipement",
            },
        ),
        migrations.AlterModelOptions(
            name="typesites",
            options={
                "verbose_name": "Typesites",
                "verbose_name_plural": "Type de site",
            },
        ),
        migrations.AlterModelOptions(
            name="typetaterrains",
            options={
                "verbose_name": "Typetaterrains",
                "verbose_name_plural": "Type de terrain",
            },
        ),
        migrations.RemoveField(
            model_name="fichenrolements",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="fichenrolements",
            name="typzone_id",
        ),
        migrations.AlterField(
            model_name="fichenrolements",
            name="type_carte",
            field=models.ForeignKey(
                blank=True,
                max_length=1000,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.typecarte",
                verbose_name="Type de carte",
            ),
        ),
    ]
