# Generated by Django 4.2.4 on 2023-11-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0002_rename_province_id_communes_province_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communes',
            old_name='commune',
            new_name='nom_comune',
        ),
    ]
