# Generated by Django 4.2.4 on 2023-11-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0002_delete_rapaccidents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formincidents',
            name='identifiant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
