# Generated by Django 4.2.4 on 2023-11-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0003_formincidents_identifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='formincidents',
            name='equipement_implique',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formincidents',
            name='personne_implique',
            field=models.TextField(blank=True, null=True),
        ),
    ]
