# Generated by Django 4.2.4 on 2023-11-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0003_rename_commune_communes_nom_comune'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communes',
            old_name='nom_comune',
            new_name='commune',
        ),
    ]
