# Generated by Django 4.2.4 on 2023-10-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paramettre", "0003_typecarte_alter_accidents_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statutsites",
            options={
                "verbose_name": "Statut du sites",
                "verbose_name_plural": "Statut du site",
            },
        ),
        migrations.AlterField(
            model_name="fichenrolements",
            name="type_carte",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.typecarte",
            ),
        ),
    ]
