# Generated by Django 4.2.4 on 2024-01-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0003_remove_message_created_remove_message_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconventions',
            name='dossiers',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Document Annexes à la signature'),
        ),
        migrations.AlterField(
            model_name='demandeconventions',
            name='point',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Coordonées du site'),
        ),
    ]
