# Generated by Django 4.2.4 on 2023-11-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0004_rename_nom_comune_communes_commune'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communes',
            name='commune',
        ),
        migrations.AddField(
            model_name='communes',
            name='nom_commune',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nom de la commune'),
        ),
    ]
