# Generated by Django 4.2.4 on 2023-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paramettre", "0004_alter_statutsites_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="typecarte",
            options={
                "verbose_name": "Type de carte",
                "verbose_name_plural": "Type de carte",
            },
        ),
        migrations.AddField(
            model_name="fichenrolements",
            name="identifiant",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
