# Generated by Django 4.2.4 on 2023-11-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0004_formincidents_equipement_implique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formincidents',
            name='mort_enf',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de Mort Enfant'),
        ),
        migrations.AlterField(
            model_name='formincidents',
            name='mort_fem',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de Mort Femme'),
        ),
        migrations.AlterField(
            model_name='formincidents',
            name='mort_hom',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de Mort Homme'),
        ),
        migrations.AlterField(
            model_name='formincidents',
            name='vict_enf',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre Victime Enfant'),
        ),
        migrations.AlterField(
            model_name='formincidents',
            name='vict_fem',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre Victime Femme'),
        ),
        migrations.AlterField(
            model_name='formincidents',
            name='vict_hom',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre Victime Homme'),
        ),
    ]
