# Generated by Django 4.2.4 on 2023-11-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0005_remove_communes_commune_communes_nom_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comsites',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='X'),
        ),
    ]
