# Generated by Django 4.2.4 on 2023-10-24 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paramettre", "0005_alter_typecarte_options_fichenrolements_identifiant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichenrolements",
            name="type_carte",
        ),
        migrations.CreateModel(
            name="LigneTypeCarte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("create_at", models.DateField(auto_now_add=True, null=True)),
                (
                    "carte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paramettre.typecarte",
                    ),
                ),
                (
                    "fiche",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paramettre.fichenrolements",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fichenrolements",
            name="type_carte",
            field=models.ManyToManyField(
                through="paramettre.LigneTypeCarte", to="paramettre.typecarte"
            ),
        ),
    ]
