# Generated by Django 4.2.4 on 2023-11-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0005_alter_formincidents_mort_enf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapactivites',
            name='identifiant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
