# Generated by Django 4.2.4 on 2024-04-17 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0005_rename_bureau_fichevisites_bureau_enc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formguidautorites',
            name='type_contrat',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='TYPE DE CONTRAT'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='accueil',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ACCUEIL\xa0DU PROMOTEUR'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='adresse',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='bureau_enc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.burencadrements', verbose_name='BE'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='champ',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='DISTANCE ENTRE LE SITE ET CHAMPS,CULTURES,ELEVAGES'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='com_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.provinces', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='com_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.regions', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='com_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.typesites', verbose_name='Type de site'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.communes', verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='cout',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='COUT D’INVESTISSEMENT\xa0'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='date_visite',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la visite'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='datum',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="DISTANCE ENTRE LE SITE ET COURS D'EAU"),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='dest',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='DESTINATION/OBTENTION DU MINERAI (ACHAT, CESSION, ETC)\xa0'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='distance1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='DISTANCE ENTRE LE SITE ET HABITATION/VILLAGES'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='distance2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="DISTANCE ENTRE LE SITE ET COURS D'EAU"),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='distance4',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Distance avec les services de santé'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='distance5',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='DISTANCE ENTRE LE SITE ET LE POSTE'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='distance6',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='SI OUI DISTANCE'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='ellipsoide',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='DISTANCE ENTRE LE SITE ET HABITATION/VILLAGES'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='entree_prod',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ENTREE EN PRODUCTION\xa0'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='extract',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='EXTRACTION/PROVENANCE\xa0'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='mode_elemi',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='MODE D’ELIMINATION DES PRODUITS CHIMIQUES CONTENUS DANS LES DECHETS\xa0'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='mode_lieu',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='MODE/LIEU D’ELIMINATION DES DECHETS\xa0'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='nom_prenom_autorite',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Nom et prenom autorité'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='nom_prenom_enqueteur',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Nom du responsable du BE'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='nom_prenom_ressouce',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nom du site'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='nom_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.comsites', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='nombre',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='NOMBRE DU PERSONNEL'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='organis',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ORGANISATION DU SITE (EN ZONES, ANARCHIQUE, ETC)'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='personne2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Nom et prenom des personnes presentes'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='point1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Coordonnées du site'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='prod_mens',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=' PRODUCTION (MENSUELLE, TRIMESTRIELLE, ETC)\xa0'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='proffe',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='PROFESSIONNALISME, SERIEUX, MAITRISE DU PROCEDE, VIABILITE DE L’EXPLOITATION'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='provenance1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='PREVENANCE'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='provenance2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='PREVENANCE'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='quali',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='QUALITE DES INFORMATIONS RECUEILLIES/COMMUNICATION\xa0'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='qualification',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='QUALIFICATION'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='qualit1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='QUALITE'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='qualit2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='QUALITE'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='qualite',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Qualité du BE'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='quantit1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='quantit2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='QUANTITE'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='reserves',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='RESERVES'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='risqu',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='RISQUES SANITAIRES ET ENVIRONNEMENTAUX\xa0(CONDITIONS DE TRAVAIL, PROCEDE'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='sante',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='SANTE(APPROVISIONNEMENT EN EAU POTABLE, POSTES DE SANTE, DISTANCE)\xa0'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='securite',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='SECURITE (POSTES) DISPONIBLE?'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='service',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='site_env',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=' SITES D’ORPAILLAGE ENVIRONNANTS (OFFICIELS ET SAUVAGES, RAYON DE 30 KM)'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='social',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ENFANTS TRAVAILLANT SUR LE SITE, ECOLES'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='traitement',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='TRAITEMENT'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='type1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='TYPE ÉQUIPEMENTS/MATERIELS'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='type2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='TYPE DE PRODUITS CHIMIQUES UTILISES '),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='type_minerai',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='TYPE DE MINERAI (BRUT, BLOC, REJETS, ETC)'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='vegeta',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='DISTANCE ENTRE LE SITE ET VEGETATION(FORET ETC..)'),
        ),
        migrations.AlterField(
            model_name='formguidautorites',
            name='village_site',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Village'),
        ),
    ]
