# Generated by Django 4.2.4 on 2023-11-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0006_alter_comsites_latitude_alter_comsites_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comsites',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Longitude'),
        ),
    ]
