# Generated by Django 4.2.4 on 2023-11-02 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0006_rapactivites_identifiant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapactivites',
            old_name='autre2',
            new_name='obs',
        ),
        migrations.RemoveField(
            model_name='rapactivites',
            name='acte',
        ),
        migrations.RemoveField(
            model_name='rapactivites',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='rapactivites',
            name='observation1',
        ),
        migrations.RemoveField(
            model_name='rapactivites',
            name='observation2',
        ),
        migrations.RemoveField(
            model_name='rapactivites',
            name='observation3',
        ),
        migrations.RemoveField(
            model_name='rapactivites',
            name='observation4',
        ),
        migrations.RemoveField(
            model_name='rapactivites',
            name='observation5',
        ),
        migrations.RemoveField(
            model_name='rapactivites',
            name='travail_enf',
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='acide',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='nombre acide'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='autre1',
            field=models.TextField(blank=True, null=True, verbose_name='si autre preciser'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='borate',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='nombre boraxe'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='burencadrement_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='BE'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='chaux',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='nombre chaux eteinte'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='cyanure',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='nombre cyanure'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='explosif',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='nombre explosif'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='mercure',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='nombre mercure'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='minerai',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='minerais disponible'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='nbr_cart_art',
            field=models.IntegerField(blank=True, null=True, verbose_name="nombre de carte d'artisant minier"),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='nbr_commite',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de commité de gestion'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='nbr_conv',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de convention'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='nbr_coop',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de cooperative'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='nbr_enf',
            field=models.IntegerField(blank=True, null=True, verbose_name="nombre d'enfant sur le site"),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='nbr_site',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de site visité'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='nbr_site_org',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de site visité'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='nouveau_site',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre nouveaux sites'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='periode',
            field=models.DateField(blank=True, null=True, verbose_name='au'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='site_ferme',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre sites fermés'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='site_reactive',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre sites reactivés'),
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='site_rehabilite',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre sites réhabilité'),
        ),
        migrations.RemoveField(
            model_name='rapactivites',
            name='type_cart_art',
        ),
        migrations.AlterField(
            model_name='rapactivites',
            name='type_com',
            field=models.CharField(blank=True, choices=[('achat', 'achat'), ('vente', 'vente'), ('fonte', 'fonte')], max_length=1000, null=True, verbose_name='Type commercial'),
        ),
        migrations.CreateModel(
            name='LigneTypeRapactivitesCarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateField(auto_created=True, auto_now_add=True, null=True)),
                ('create_at', models.DateField(auto_now_add=True, null=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.rapactivites')),
                ('typecarte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.typecarte')),
            ],
        ),
        migrations.AddField(
            model_name='rapactivites',
            name='type_cart_art',
            field=models.ManyToManyField(through='paramettre.LigneTypeRapactivitesCarte', to='paramettre.typecarte'),
        ),
    ]
