# Generated by Django 4.2.4 on 2023-11-18 12:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0007_alter_comsites_latitude_alter_comsites_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='comsites',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Coordonnées'),
        ),
    ]
