# Generated by Django 4.2.4 on 2023-11-02 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0007_rename_autre2_rapactivites_obs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapactivites',
            name='burencadrement_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.burencadrements', verbose_name='BE'),
        ),
    ]
