# Generated by Django 4.2.4 on 2023-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paramettre", "0007_remove_lignetypecarte_quantite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichenrolements",
            name="num_carte",
            field=models.CharField(blank=True, null=True),
        ),
    ]
