# Generated by Django 4.2.4 on 2023-11-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0008_comsites_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comsites',
            name='point',
        ),
    ]
