# Generated by Django 4.2.4 on 2023-11-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0008_alter_rapactivites_burencadrement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapactivites',
            old_name='periode',
            new_name='periode2',
        ),
        migrations.AddField(
            model_name='rapactivites',
            name='periode1',
            field=models.DateField(blank=True, null=True, verbose_name='periode du'),
        ),
    ]
