# Generated by Django 4.2.4 on 2023-10-24 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paramettre", "0008_alter_fichenrolements_num_carte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichevisites",
            name="com_province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.provinces",
            ),
        ),
        migrations.AlterField(
            model_name="fichevisites",
            name="com_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.regions",
            ),
        ),
        migrations.AlterField(
            model_name="fichevisites",
            name="com_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.typesites",
            ),
        ),
        migrations.AlterField(
            model_name="fichevisites",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.communes",
            ),
        ),
        migrations.AlterField(
            model_name="fichevisites",
            name="nbr_enfant",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fichevisites",
            name="nbr_fem",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fichevisites",
            name="nbr_hom",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fichevisites",
            name="point1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fichevisites",
            name="point2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fichevisites",
            name="point3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fichevisites",
            name="point4",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
