# Generated by Django 4.2.4 on 2023-11-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0009_rename_periode_rapactivites_periode2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheprelevements',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='ficheprelevements',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ficheprelevements',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='ficheprelevements',
            name='precision',
        ),
        migrations.AddField(
            model_name='ficheprelevements',
            name='coordonnees',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ficheprelevements',
            name='coordonnees_manu',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ficheprelevements',
            name='identifiant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
