# Generated by Django 4.2.4 on 2023-11-18 20:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0009_remove_comsites_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='comsites',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Coordonnées'),
        ),
    ]
