# Generated by Django 4.2.4 on 2023-10-24 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paramettre", "0009_alter_fichevisites_com_province_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Formdsracs",
        ),
        migrations.RemoveField(
            model_name="formguidautorites",
            name="province",
        ),
        migrations.RemoveField(
            model_name="formguidautorites",
            name="region",
        ),
        migrations.RemoveField(
            model_name="formguidautorites",
            name="village",
        ),
        migrations.AddField(
            model_name="formguidautorites",
            name="com_province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.provinces",
            ),
        ),
        migrations.AddField(
            model_name="formguidautorites",
            name="com_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.regions",
            ),
        ),
        migrations.AddField(
            model_name="formguidautorites",
            name="com_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.typesites",
            ),
        ),
        migrations.AlterField(
            model_name="formguidautorites",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.communes",
            ),
        ),
    ]
