# Generated by Django 4.2.4 on 2023-10-25 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "paramettre",
            "0010_delete_formdsracs_remove_formguidautorites_province_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communes",
            name="id_2",
        ),
        migrations.RemoveField(
            model_name="provinces",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="regions",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="typenatureminerais",
            name="flag_actif",
        ),
        migrations.RemoveField(
            model_name="typenatureterrains",
            name="flag_actif",
        ),
        migrations.RemoveField(
            model_name="typeorganisations",
            name="flag_actif",
        ),
        migrations.RemoveField(
            model_name="typeproduitchimiques",
            name="flag_actif",
        ),
        migrations.RemoveField(
            model_name="typequipements",
            name="flag_actif",
        ),
        migrations.RemoveField(
            model_name="typesites",
            name="flag_actif",
        ),
        migrations.RemoveField(
            model_name="typetaterrains",
            name="flag_actif",
        ),
        migrations.AddField(
            model_name="comsites",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.communes",
            ),
        ),
        migrations.AlterField(
            model_name="communes",
            name="province_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.provinces",
            ),
        ),
        migrations.AlterField(
            model_name="comsites",
            name="cat_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.categories",
            ),
        ),
        migrations.AlterField(
            model_name="comsites",
            name="code_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.typesites",
            ),
        ),
        migrations.AlterField(
            model_name="comsites",
            name="latitude",
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="comsites",
            name="longitude",
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="formguidautorites",
            name="statut_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.statutsites",
            ),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="region_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.regions",
            ),
        ),
    ]
