# Generated by Django 4.2.4 on 2023-11-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0010_remove_ficheprelevements_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheprelevements',
            name='nom_preleveur',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Nom et Prenom du preleveur'),
        ),
        migrations.AlterField(
            model_name='ficheprelevements',
            name='nom_personnes_commandiaire',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Nom et Prenom du commanditaire'),
        ),
    ]
