# Generated by Django 4.2.4 on 2023-10-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paramettre", "0011_remove_communes_id_2_remove_provinces_numero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formguidautorites",
            name="date_visite",
            field=models.DateField(blank=True, null=True),
        ),
    ]
