# Generated by Django 4.2.4 on 2023-11-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0011_ficheprelevements_nom_preleveur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheprelevements',
            name='commune',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
