# Generated by Django 4.2.4 on 2023-11-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0012_alter_ficheprelevements_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichevisites',
            name='identifiant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichexpminieres',
            name='identifiant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formguidautorites',
            name='identifiant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
