# Generated by Django 4.2.4 on 2023-10-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paramettre", "0013_rename_point1_fichevisites_altitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formguidautorites",
            name="nom_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.comsites",
            ),
        ),
    ]
