# Generated by Django 4.2.4 on 2023-11-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0014_rename_produit1_fichexpminieres_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichexpminieres',
            name='q160',
        ),
        migrations.RemoveField(
            model_name='fichexpminieres',
            name='q181',
        ),
        migrations.RemoveField(
            model_name='fichexpminieres',
            name='q182',
        ),
        migrations.RemoveField(
            model_name='fichexpminieres',
            name='q183',
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='distance10',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance moyenne avec les ecoles'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='distance7',
            field=models.FloatField(blank=True, null=True, verbose_name="Distance moyenne des sources d'approvisonnement en eaux"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='distance8',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance moyenne des postes de santé'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='distance9',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance moyenne des postes de securité'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='nb_arbre_coupe',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'arbre coupé"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='nb_arbre_reboise',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'arbre reboisé"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='nb_arbre_survecu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Nombre d'arbre reboisé ayant survecu"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='nb_puits2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de puits artisanal productif'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='nb_puits3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de puits artisanal abandonné'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='paiement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Taxe anuelle'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q12',
            field=models.CharField(blank=True, choices=[('nouveau', 'Nouveau'), ('ancien', 'Ancien'), ('reconnu', 'Reconnu ou non'), ('organise', 'Organisé ou non'), ('insatnce', 'Dossier en instance')], max_length=300, null=True, verbose_name='Situation administrative'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q132',
            field=models.FloatField(blank=True, null=True, verbose_name='Tonage des rejet de produits'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q142',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name="Respect des date d'interdiction"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q149',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name='Port des ecquipement de portection'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q150',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name='Consommation de stupefiants'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q151',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name='Postitution'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q152',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name='Postitution infantile'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q153',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name='Délinquance'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q154',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name='Criminalité'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q155',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name="Utilisation d'explosif"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q156',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre de boutique d'alcool"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q157',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'explositifs accidentel"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q158',
            field=models.FloatField(blank=True, null=True, verbose_name='Superficie du site'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q159',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name='Site protégé '),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q161',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name='site à haute valeur de conservation'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q163',
            field=models.FloatField(blank=True, null=True, verbose_name='Superficie pertubée'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q167',
            field=models.CharField(blank=True, choices=[('tres_faible', 'Très faible'), ('faible', 'faible'), ('moyen', 'moyen'), ('assez_eleve', ' Assez élevé'), ('eleve', 'élevé'), ('tres_eleve', '  Très élevé')], max_length=200, null=True, verbose_name="Niveau d'utilisation du mercure"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q168',
            field=models.CharField(blank=True, choices=[('tres_faible', 'Très faible'), ('faible', 'faible'), ('moyen', 'moyen'), ('assez_eleve', ' Assez élevé'), ('eleve', 'élevé'), ('tres_eleve', '  Très élevé')], max_length=200, null=True, verbose_name="Niveau d'utilisation du acide"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q169',
            field=models.CharField(blank=True, choices=[('tres_faible', 'Très faible'), ('faible', 'faible'), ('moyen', 'moyen'), ('assez_eleve', ' Assez élevé'), ('eleve', 'élevé'), ('tres_eleve', '  Très élevé')], max_length=200, null=True, verbose_name="Niveau d'emmission de la poussiere"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q170',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name="Presence d'hydrocarbure"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q171',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name="Presence d'Eau de l'amalgamationor-mercure"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q172',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name="Presence d'Eau de cyanure"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q173',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name='Presence de bassin de cyanure'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q174',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name="Presence d'eau usée dans les espace de traitement"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q175',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name="Presence  d'eau usée menagère"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q176',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Presence dordure menagère'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q177',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Presence d'excreta"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q178',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=200, null=True, verbose_name='Bonne acceuil du promoteur'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q179',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Qualité des informations receuilli'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q180',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='q9',
            field=models.CharField(blank=True, choices=[('OUI', 'oui'), ('NON', 'non')], max_length=300, null=True, verbose_name='Presence de champs ou culture?'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='qe166',
            field=models.CharField(blank=True, choices=[('tres_faible', 'Très faible'), ('faible', 'faible'), ('moyen', 'moyen'), ('assez_eleve', ' Assez élevé'), ('eleve', 'élevé'), ('tres_eleve', '  Très élevé')], max_length=200, null=True, verbose_name="Niveau d'utilisation du cyanure"),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='rapport_promoteur_orpailleurs',
            field=models.CharField(blank=True, choices=[('BON', 'BON'), ('TENSION', 'TENSION')], max_length=2000, null=True, verbose_name='Rapport promoteur/Artisan'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='rapport_promoteur_population',
            field=models.CharField(blank=True, choices=[('BON', 'BON'), ('TENSION', 'TENSION')], max_length=2000, null=True, verbose_name='Rapport promoteur/Population'),
        ),
    ]
