# Generated by Django 4.2.4 on 2023-11-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0015_remove_fichexpminieres_q160_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichexpminieres',
            name='d_fin',
            field=models.DateField(blank=True, max_length=300, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='d_renouv',
            field=models.DateField(blank=True, max_length=300, null=True, verbose_name='Date de renouvelmenet'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='distance1',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='Distence entre le site et les habitations'),
        ),
        migrations.AlterField(
            model_name='fichexpminieres',
            name='distance2',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name="Distence entre le site et les cours d'eaux"),
        ),
    ]
