# Generated by Django 4.2.4 on 2023-10-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paramettre", "0015_rename_commune2_id_demandeconventions_commune_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandeconventions",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.communes",
            ),
        ),
        migrations.AlterField(
            model_name="demandeconventions",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.provinces",
            ),
        ),
        migrations.AlterField(
            model_name="demandeconventions",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.regions",
            ),
        ),
    ]
