# Generated by Django 4.2.4 on 2023-11-09 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0016_alter_fichexpminieres_d_fin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accidents',
        ),
        migrations.DeleteModel(
            name='Incidents',
        ),
        migrations.AddField(
            model_name='comsites',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comsites',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='cat_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.categories', verbose_name='Categorie de site'),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='code_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.typesites', verbose_name='Type de site'),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='date_deb_expl',
            field=models.DateField(blank=True, null=True, verbose_name="Date debut d'exploitation"),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='date_fin_exp',
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin d'exploitation"),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='nom_site',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Npm du de site'),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.statutsites', verbose_name='Stut de site'),
        ),
        migrations.AlterField(
            model_name='formincidents',
            name='type_rapport',
            field=models.CharField(blank=True, choices=[('accident', 'ACCIDENT'), ('incident', 'INCIDENT')], default='incident', max_length=1500, null=True),
        ),
    ]
