# Generated by Django 4.2.4 on 2023-10-25 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paramettre", "0017_remove_demandeconventions_fichier1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ficheprelevements",
            old_name="adresse",
            new_name="adresse_personnes_commandiaire",
        ),
        migrations.RenameField(
            model_name="ficheprelevements",
            old_name="date_prelev",
            new_name="date_prelevement",
        ),
        migrations.RenameField(
            model_name="ficheprelevements",
            old_name="nb_flacons_p",
            new_name="nombre_flacons_plastique",
        ),
        migrations.RenameField(
            model_name="ficheprelevements",
            old_name="nb_flacons_v",
            new_name="nombre_flacons_verre",
        ),
        migrations.RenameField(
            model_name="ficheprelevements",
            old_name="commune_id",
            new_name="point_prelevement",
        ),
        migrations.RemoveField(
            model_name="ficheprelevements",
            name="coord_gps",
        ),
        migrations.RemoveField(
            model_name="ficheprelevements",
            name="coord_man_x",
        ),
        migrations.RemoveField(
            model_name="ficheprelevements",
            name="coord_man_y",
        ),
        migrations.RemoveField(
            model_name="ficheprelevements",
            name="nom_personne1",
        ),
        migrations.RemoveField(
            model_name="ficheprelevements",
            name="nom_personne2",
        ),
        migrations.RemoveField(
            model_name="ficheprelevements",
            name="point",
        ),
        migrations.AddField(
            model_name="ficheprelevements",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paramettre.communes",
            ),
        ),
        migrations.AddField(
            model_name="ficheprelevements",
            name="nom_personnes_commandiaire",
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name="ficheprelevements",
            name="altitude",
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="ficheprelevements",
            name="latitude",
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="ficheprelevements",
            name="longitude",
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="ficheprelevements",
            name="precision",
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
    ]
