# Generated by Django 4.2.4 on 2023-10-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "paramettre",
            "0018_rename_adresse_ficheprelevements_adresse_personnes_commandiaire_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="fichexpminieres",
            old_name="comentaire1",
            new_name="comentaire",
        ),
        migrations.RenameField(
            model_name="fichexpminieres",
            old_name="commune1_id",
            new_name="commune",
        ),
        migrations.RenameField(
            model_name="fichexpminieres",
            old_name="province1_id",
            new_name="province",
        ),
        migrations.RenameField(
            model_name="fichexpminieres",
            old_name="region1_id",
            new_name="region",
        ),
        migrations.RenameField(
            model_name="fichexpminieres",
            old_name="resultat1",
            new_name="resultat",
        ),
        migrations.AddField(
            model_name="fichexpminieres",
            name="date_la_mission",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fichexpminieres",
            name="site_a_cheval",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
