# Generated by Django 4.2.4 on 2023-11-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0019_demandeconventions_dossiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconventions',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name="Document Annexes à l'instruction"),
        ),
    ]
