# Generated by Django 4.2.4 on 2023-11-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0020_alter_demandeconventions_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconventions',
            name='concertation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='demandeconventions',
            name='organisation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='demandeconventions',
            name='plan_masse',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='demandeconventions',
            name='pv_constat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='demandeconventions',
            name='reconnaissance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
