# Generated by Django 4.2.4 on 2023-11-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0021_alter_demandeconventions_concertation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeconventions',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='demandeconventions',
            name='renonce',
        ),
        migrations.RemoveField(
            model_name='demandeconventions',
            name='retire',
        ),
        migrations.AlterField(
            model_name='demandeconventions',
            name='dossiers',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name="Document Annexes à l'instruction"),
        ),
    ]
