# Generated by Django 4.2.4 on 2023-11-10 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0023_alter_demandeconventions_exploitant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formincidents',
            name='nom_site',
            field=models.ForeignKey(blank=True, max_length=2500, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.comsites'),
        ),
    ]
