# Generated by Django 4.2.4 on 2023-11-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0024_alter_formincidents_nom_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formincidents',
            name='date_incident',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
