# Generated by Django 4.2.4 on 2023-11-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0025_alter_formincidents_date_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formincidents',
            name='date_incident',
            field=models.DateField(blank=True, null=True),
        ),
    ]
