# Generated by Django 4.2.4 on 2023-11-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0026_alter_formincidents_date_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheprelevements',
            name='nat_eau',
            field=models.CharField(blank=True, choices=[('surface', 'surface'), ('souterrain', 'souterrain')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ficheprelevements',
            name='type_nature_echant',
            field=models.CharField(blank=True, choices=[('eaux', 'eaux'), ('sol', 'sol')], max_length=1000, null=True),
        ),
    ]
