# Generated by Django 4.2.4 on 2023-11-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0027_ficheprelevements_nat_eau_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Norme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paramettre', models.CharField(blank=True, max_length=100, null=True)),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('unités', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ficheprelevements',
            name='nat_eau',
            field=models.CharField(blank=True, choices=[('surface', 'surface'), ('souterrain', 'souterrain')], max_length=1000, null=True, verbose_name='Nature eaux'),
        ),
        migrations.AlterField(
            model_name='ficheprelevements',
            name='type_nature_echant',
            field=models.CharField(blank=True, choices=[('eaux', 'eaux'), ('sol', 'sol')], max_length=1000, null=True, verbose_name='Nature echantillon'),
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductivite', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('tds', models.FloatField(blank=True, null=True)),
                ('oxigene_dissous', models.FloatField(blank=True, null=True)),
                ('turbidite', models.FloatField(blank=True, null=True)),
                ('bruit', models.CharField(blank=True, max_length=1000, null=True)),
                ('odeur', models.CharField(blank=True, max_length=1000, null=True)),
                ('lumiere', models.CharField(blank=True, max_length=1000, null=True)),
                ('prelevement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.ficheprelevements')),
            ],
        ),
    ]
