# Generated by Django 4.2.4 on 2023-11-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0028_norme_alter_ficheprelevements_nat_eau_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='norme',
            old_name='unités',
            new_name='unites',
        ),
    ]
