# Generated by Django 4.2.4 on 2023-11-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0030_analyse_created_analyse_modified_norme_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formincidents',
            name='type',
        ),
    ]
