# Generated by Django 4.2.4 on 2023-11-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0033_remove_comsites_cat_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comsites',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='comsites',
            name='precision',
        ),
    ]
