# Generated by Django 4.2.4 on 2023-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0034_remove_comsites_altitude_remove_comsites_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comsites',
            name='etendu',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Etendu du site en (m)'),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='latitude',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='latitude1',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Y2'),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='longitude',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='comsites',
            name='longitude1',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='X2'),
        ),
    ]
