# Generated by Django 4.2.4 on 2023-12-05 23:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paramettre', '0011_remove_comsites_point'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(max_length=60)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('reference_societe', models.CharField(blank=True, max_length=1024, null=True)),
                ('pays', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlBUMIGEB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateTimeField(auto_now_add=True)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('out', 'En cours'), ('in', 'Terminé')], default='out', max_length=10)),
                ('numero_lot', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('observation', models.TextField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('reintegrer_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reintegrer_par', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmplacementLingot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type_emplacement', models.CharField(choices=[('in', 'Interne'), ('out', 'Externe')], default='out', max_length=20)),
                ('pays', django_countries.fields.CountryField(default='BF', max_length=2)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Emplacements Lingots',
            },
        ),
        migrations.CreateModel(
            name='FactureDefinitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Factures definitives',
            },
        ),
        migrations.CreateModel(
            name='FactureProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('numero', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('source_de_poids', models.CharField(choices=[('poids_lingots', 'Poids SONASP'), ('poids_bumigeb', 'Poids BUMIGEB'), ('pourcentage_lingots', 'Pourcentage SONASP'), ('pourcentage_bumigeb', 'Pourcentage BUMIGEB')], max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Facture proforma',
            },
        ),
        migrations.CreateModel(
            name='Fichecontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=256, null=True)),
                ('date_control', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Fiches de Control',
            },
        ),
        migrations.CreateModel(
            name='FicheTarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('marge', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('date_tarification', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('observation', models.CharField(blank=True, max_length=256, null=True)),
                ('numero', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('transferer', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('fichecontrol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichecontrol')),
            ],
            options={
                'verbose_name_plural': 'Fiches de Tarification',
            },
        ),
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateTimeField(auto_now_add=True)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('out', 'En cours'), ('in', 'Fondu')], default='out', max_length=10)),
                ('observation', models.CharField(blank=True, max_length=256, null=True)),
                ('fondu', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('valider_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valider_par', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=60, null=True)),
                ('nom', models.CharField(blank=True, max_length=60, null=True)),
                ('numero_carte', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=60)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cartartisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.cartartisants')),
            ],
            options={
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Lingot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poids_brut', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('poids_immerge', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ecart', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('densite', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('titre', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('or_fin', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('numero_bumigeb', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('poids_brut_bumigeb', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('poids_immerge_bumigeb', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ecart_bumigeb', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('or_fin_bumigeb', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('densite_bumigeb', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('titre_bumigeb', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('observation_bumigeb', models.TextField(blank=True, max_length=256, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('is_fonte', models.BooleanField(default=False)),
                ('avendre', models.BooleanField(default=False)),
                ('control_bumigeb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.controlbumigeb')),
                ('fichecontrol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichecontrol')),
                ('fonte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fonte')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fournisseur')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lingots',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ModePayement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60)),
                ('actif', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('readonly', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Modes de payements',
            },
        ),
        migrations.CreateModel(
            name='MouvementLingot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('start', 'En cours'), ('end', 'Terminé')], default='start', max_length=20)),
                ('numero_mouvement', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_deplacement', models.DateTimeField(auto_now_add=True)),
                ('date_arrive', models.DateTimeField(auto_now_add=True, null=True)),
                ('archived', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.emplacementlingot')),
            ],
            options={
                'verbose_name_plural': 'Mouvements Lingots',
            },
        ),
        migrations.CreateModel(
            name='RapportAffinage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('numero_lingot_rapport', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('poids_brut', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('poids_immerge', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ecart', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('or_fin', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('densite', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('titre_carat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('observation', models.TextField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rapports affinage',
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Telephones',
            },
        ),
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Types clients',
            },
        ),
        migrations.CreateModel(
            name='TypeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Types fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='TypeSubstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('symbole', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Types Substances',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('date_conclusion', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('numero', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('conclu', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.client')),
                ('facture_definitive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.facturedefinitive')),
                ('facture_proforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.factureproforma')),
                ('rapport_affinage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.rapportaffinage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ventes',
            },
        ),
        migrations.CreateModel(
            name='StragieTarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('application_auto', models.BooleanField(default=False)),
                ('marge', models.DecimalField(decimal_places=4, max_digits=10)),
                ('marge_auto', models.BooleanField(default=True)),
                ('cours', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cours_auto', models.BooleanField(default=True)),
                ('globale', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type_fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.typefournisseur')),
            ],
            options={
                'verbose_name_plural': 'Strategies de tarifications',
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=256)),
                ('libelle', models.CharField(blank=True, max_length=60, null=True)),
                ('Telephones', models.ManyToManyField(blank=True, to='commercial.telephone')),
                ('clients', models.ManyToManyField(blank=True, to='commercial.client')),
                ('fournisseurs', models.ManyToManyField(blank=True, to='commercial.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='RepresentantFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=60, null=True)),
                ('nom', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(max_length=60)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.fournisseur')),
            ],
            options={
                'verbose_name_plural': 'Representants fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='media/attachments/commercial/')),
                ('description', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Pesee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_brut', models.DecimalField(decimal_places=4, max_digits=10)),
                ('poids_immerge', models.DecimalField(decimal_places=4, max_digits=10)),
                ('observation', models.CharField(blank=True, max_length=256, null=True)),
                ('date_pesee', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('lingot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.lingot')),
            ],
            options={
                'verbose_name_plural': 'Pesees',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('numero', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('reference_payement', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('document_payement', models.FileField(blank=True, null=True, unique=True, upload_to='uploads/commercial')),
                ('recu_payement', models.FileField(blank=True, null=True, unique=True, upload_to='uploads/commercial')),
                ('document_identite', models.FileField(blank=True, null=True, upload_to='uploads/commercial')),
                ('reference_document_identite', models.CharField(blank=True, max_length=16, null=True)),
                ('autre_document', models.FileField(blank=True, null=True, upload_to='uploads/commercial')),
                ('direction', models.CharField(choices=[('in', 'ENTREE'), ('out', 'SORTIE')], default='ENTREE', max_length=6)),
                ('observation', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('confirme', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('fichetarification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichetarification')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fournisseur')),
                ('mode_payement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.modepayement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='MouvementLingotLingot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved', models.BooleanField(default=False)),
                ('lingot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.lingot')),
                ('mouvement_lingot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.mouvementlingot')),
            ],
        ),
        migrations.AddField(
            model_name='mouvementlingot',
            name='lingots',
            field=models.ManyToManyField(through='commercial.MouvementLingotLingot', to='commercial.lingot'),
        ),
        migrations.AddField(
            model_name='mouvementlingot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LingotFondus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercial.fonte')),
                ('lingot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercial.lingot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lingot',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.vente'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='type_fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.typefournisseur'),
        ),
        migrations.AddField(
            model_name='fichetarification',
            name='representant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.representantfournisseur'),
        ),
        migrations.AddField(
            model_name='fichetarification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichecontrol',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fournisseur'),
        ),
        migrations.AddField(
            model_name='fichecontrol',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Factures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('fiche_tarification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.lingot')),
            ],
            options={
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='DirectionLingot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions_destination', to='commercial.emplacementlingot')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions_origin', to='commercial.emplacementlingot')),
                ('type_substance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.typesubstance')),
            ],
            options={
                'verbose_name_plural': 'Directions Lingots',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.typeclient'),
        ),
        migrations.CreateModel(
            name='LingotsDisponiblesPourVente',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Lingots disponibles vente',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commercial.lingot',),
        ),
        migrations.CreateModel(
            name='TransferedFicheTarification',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Paiements en attentes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commercial.fichetarification',),
        ),
        migrations.CreateModel(
            name='TransferedLingot',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Lingots transférés',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commercial.lingot',),
        ),
        migrations.CreateModel(
            name='VentesConclu',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Ventes conclu',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commercial.vente',),
        ),
        migrations.CreateModel(
            name='PourcentageSubstanceRapportAffinage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('reste', models.BooleanField(default=False)),
                ('rapport_affinage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.rapportaffinage')),
                ('type_substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.typesubstance')),
            ],
            options={
                'verbose_name': 'Pourcentage des substance',
                'verbose_name_plural': 'Pourcentage des substances',
                'unique_together': {('rapport_affinage', 'type_substance')},
            },
        ),
        migrations.CreateModel(
            name='PourcentageSubstanceLingot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('reste', models.BooleanField(default=False)),
                ('lingot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.lingot')),
                ('type_substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.typesubstance')),
            ],
            options={
                'verbose_name': 'Pourcentage des substance',
                'verbose_name_plural': 'Pourcentage des substances',
                'unique_together': {('lingot', 'type_substance')},
            },
        ),
        migrations.CreateModel(
            name='PourcentageSubstanceControlLingot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('reste', models.BooleanField(default=False)),
                ('lingot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.lingot')),
                ('type_substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.typesubstance')),
            ],
            options={
                'verbose_name': 'Pourcentage des substance',
                'verbose_name_plural': 'Pourcentage des substances',
                'unique_together': {('lingot', 'type_substance')},
            },
        ),
        migrations.CreateModel(
            name='PourcentageSubstanceControlBUMIGEB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('reste', models.BooleanField(default=False)),
                ('control_bumigeb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.controlbumigeb')),
                ('type_substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.typesubstance')),
            ],
            options={
                'verbose_name': 'Pourcentage des substance',
                'verbose_name_plural': 'Pourcentage des substances',
                'unique_together': {('control_bumigeb', 'type_substance')},
            },
        ),
        migrations.CreateModel(
            name='ControlLingot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('type', models.CharField(choices=[('bumigeb', 'Control BUMIGEB'), ('affinage', 'Rapport affinage'), ('sonasp', 'Control SONASP'), ('autre', 'Autre type de control')], default='bumigeb', max_length=20)),
                ('numero_lingot_control', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('poids_brut', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('poids_immerge', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ecart', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('or_fin', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('densite', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('titre_carat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('observation', models.TextField(blank=True, max_length=256, null=True)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.control')),
                ('lingot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.lingot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Control Lingots',
                'unique_together': {('control', 'lingot')},
            },
        ),
    ]
