# Generated by Django 4.2.4 on 2023-11-02 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paramettre', '0019_rename_comentaire1_fichexpminieres_comentaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmplacementLingot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fichecontrol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observation', models.CharField(max_length=256)),
                ('date_control', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fiches de Control',
            },
        ),
        migrations.CreateModel(
            name='FicheTarification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observation', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_tarification', models.DateTimeField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fiche_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichecontrol')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fiches de Tarification',
            },
        ),
        migrations.CreateModel(
            name='Lingot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poids_brut', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('poids_immerge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ecart', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('densite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('titre_carat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantite_or_fin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_reception', models.DateTimeField(blank=True)),
                ('observation', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.emplacementlingot')),
                ('fiche_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichecontrol')),
                ('fiche_tarification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichetarification')),
            ],
            options={
                'verbose_name_plural': 'Lingots',
            },
        ),
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Type de client',
            },
        ),
        migrations.CreateModel(
            name='TypeLingot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StragieTarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('marge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marge_auto', models.BooleanField(blank=True, default=True, null=True)),
                ('cours', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cours_auto', models.BooleanField(blank=True, default=True, null=True)),
                ('globale', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('type_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.typeclient')),
            ],
            options={
                'verbose_name_plural': 'Strategies de tarifications',
            },
        ),
        migrations.CreateModel(
            name='Pesee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_brut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poids_immerge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('titre_carat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantite_or_fin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_pesee', models.DateField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('valide', models.BooleanField(default=True)),
                ('lingot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.lingot')),
            ],
            options={
                'verbose_name_plural': 'Pesees',
            },
        ),
        migrations.CreateModel(
            name='MovementLingot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('debut', 'Début'), ('encours', 'En cours'), ('arrive', 'Arrivé')], max_length=20)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_arrive', models.DateTimeField(auto_now_add=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_destination', to='commercial.emplacementlingot')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_origin', to='commercial.emplacementlingot')),
                ('type_lingot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.typelingot')),
            ],
            options={
                'verbose_name_plural': 'Mouvements Lingots',
            },
        ),
        migrations.AddField(
            model_name='lingot',
            name='type_lingot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.typelingot'),
        ),
        migrations.AddField(
            model_name='lingot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Factures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('numero_facture', models.CharField(blank=True, max_length=50, null=True)),
                ('fiche_tarification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.lingot')),
            ],
            options={
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions_destination', to='commercial.emplacementlingot')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions_origin', to='commercial.emplacementlingot')),
                ('type_lingot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.typelingot')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=60, null=True)),
                ('prenom', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cartartisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramettre.cartartisants')),
                ('type_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.typeclient')),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
