# Generated by Django 4.2.4 on 2023-11-04 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lingot',
            name='fonte',
        ),
        migrations.AddField(
            model_name='fonte',
            name='lingot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commercial.lingot'),
            preserve_default=False,
        ),
    ]
