# Generated by Django 4.2.4 on 2023-11-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('numero_facture', models.CharField(blank=True, max_length=50, null=True)),
                ('fiche_tarification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.lingot')),
            ],
        ),
    ]
