# Generated by Django 4.2.4 on 2023-11-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stragietarification',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stragietarification',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
