# Generated by Django 4.2.4 on 2023-11-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_remove_lingot_fonte_fonte_lingot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonte',
            name='lingot',
        ),
        migrations.AddField(
            model_name='fonte',
            name='lingots',
            field=models.ManyToManyField(to='commercial.lingot'),
        ),
    ]
