# Generated by Django 4.2.4 on 2023-12-05 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_alter_fichecontrol_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
