# Generated by Django 4.2.4 on 2023-11-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_rename_direction_directionlingot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionlingot',
            options={'verbose_name_plural': 'Directions Lingots'},
        ),
        migrations.AlterModelOptions(
            name='emplacementlingot',
            options={'verbose_name_plural': 'Emplacements Lingots'},
        ),
        migrations.AddField(
            model_name='emplacementlingot',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
