# Generated by Django 4.2.4 on 2023-11-01 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_typeclient_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmplacementLingot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeLingot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovementLingot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('debut', 'Début'), ('encours', 'En cours'), ('arrive', 'Arrivé')], max_length=20)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_arrive', models.DateTimeField(auto_now_add=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_destination', to='commercial.emplacementlingot')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_origin', to='commercial.emplacementlingot')),
                ('type_lingot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.typelingot')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions_destination', to='commercial.emplacementlingot')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions_origin', to='commercial.emplacementlingot')),
                ('type_lingot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.typelingot')),
            ],
        ),
        migrations.AddField(
            model_name='lingot',
            name='emplacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.emplacementlingot'),
        ),
        migrations.AddField(
            model_name='lingot',
            name='type_lingot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.typelingot'),
        ),
    ]
