# Generated by Django 4.2.4 on 2023-12-06 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_alter_payement_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pourcentagesubstancecontrollingot',
            name='control_lingot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commercial.controllingot'),
            preserve_default=False,
        ),
    ]
