# Generated by Django 4.2.4 on 2023-11-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_remove_fonte_lingot_fonte_lingots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichetarification',
            name='fiche_control',
        ),
        migrations.RemoveField(
            model_name='lingot',
            name='emplacement',
        ),
        migrations.RemoveField(
            model_name='lingot',
            name='fiche_control',
        ),
        migrations.RemoveField(
            model_name='lingot',
            name='fiche_tarification',
        ),
        migrations.RemoveField(
            model_name='lingot',
            name='type_lingot',
        ),
        migrations.AddField(
            model_name='fichecontrol',
            name='fiche_tarification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichetarification'),
        ),
        migrations.AddField(
            model_name='fichecontrol',
            name='lingots',
            field=models.ManyToManyField(to='commercial.lingot'),
        ),
    ]
