# Generated by Django 4.2.4 on 2023-11-01 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_emplacementlingot_typelingot_movementlingot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StragieTarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('globale', models.BooleanField(default=False)),
                ('marge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cours', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cours_auto', models.BooleanField(blank=True, default=True, null=True)),
                ('marge_auto', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
