# Generated by Django 4.2.4 on 2023-11-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_alter_directionlingot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionlingot',
            name='type_lingot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.typelingot'),
        ),
    ]
