# Generated by Django 4.2.4 on 2023-11-04 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_remove_fichetarification_fiche_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesee',
            name='date_pesee',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
