# Generated by Django 4.2.4 on 2023-12-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_pourcentagesubstancecontrollingot_control_lingot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllingot',
            name='type',
            field=models.CharField(choices=[('bumigeb', 'Control BUMIGEB'), ('affinage', 'Rapport affinage'), ('sonasp', 'Control SONASP')], default='bumigeb', max_length=20),
        ),
        migrations.AlterField(
            model_name='factureproforma',
            name='source_de_poids',
            field=models.CharField(choices=[('bumigeb', 'Control BUMIGEB'), ('affinage', 'Rapport affinage'), ('sonasp', 'Control SONASP')], max_length=20),
        ),
    ]
