# Generated by Django 4.2.4 on 2023-11-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_alter_pesee_date_pesee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lingot',
            name='date_reception',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesee',
            name='date_pesee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
