# Generated by Django 4.2.4 on 2023-12-06 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_alter_controllingot_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factureproforma',
            old_name='source_de_poids',
            new_name='poids_selon',
        ),
    ]
