# Generated by Django 4.2.4 on 2023-11-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_alter_directionlingot_type_lingot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovementLingot',
            new_name='MouvementLingot',
        ),
        migrations.AlterModelOptions(
            name='typeclient',
            options={'verbose_name_plural': 'Types de clients'},
        ),
        migrations.AlterModelOptions(
            name='typelingot',
            options={'verbose_name_plural': 'Types de Lingots'},
        ),
    ]
