# Generated by Django 4.2.4 on 2023-11-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_alter_lingot_date_reception_alter_pesee_date_pesee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichecontrol',
            name='lingots',
        ),
        migrations.AddField(
            model_name='lingot',
            name='fichecontrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichecontrol'),
        ),
    ]
