# Generated by Django 4.2.4 on 2023-12-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_rename_source_de_poids_factureproforma_poids_selon'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureproforma',
            name='cours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichetarification',
            name='cours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
