# Generated by Django 4.2.4 on 2023-11-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0007_remove_fichecontrol_lingots_lingot_fichecontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichecontrol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
