# Generated by Django 4.2.4 on 2023-12-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_alter_factureproforma_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.vente'),
        ),
        migrations.AddField(
            model_name='vente',
            name='control_choisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_choisi', to='commercial.control'),
        ),
    ]
