# Generated by Django 4.2.4 on 2023-11-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_modepayement_fonte_lingot_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='stragietarification',
            name='application_auto',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
