# Generated by Django 4.2.4 on 2023-11-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_alter_fichecontrol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichecontrol',
            name='observation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
