# Generated by Django 4.2.4 on 2023-11-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0009_stragietarification_application_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stragietarification',
            name='application_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stragietarification',
            name='cours_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stragietarification',
            name='marge_auto',
            field=models.BooleanField(default=True),
        ),
    ]
