# Generated by Django 4.2.4 on 2023-12-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0009_control_vente_vente_control_choisi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controllingot',
            old_name='type',
            new_name='type_control',
        ),
        migrations.AddField(
            model_name='control',
            name='type_control',
            field=models.CharField(choices=[('bumigeb', 'Control BUMIGEB'), ('affinage', 'Rapport affinage'), ('sonasp', 'Control SONASP')], default='bumigeb', max_length=20),
        ),
    ]
