# Generated by Django 4.2.4 on 2023-11-08 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0009_alter_fichecontrol_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='numero_facture',
        ),
        migrations.RemoveField(
            model_name='fichecontrol',
            name='fiche_tarification',
        ),
        migrations.AddField(
            model_name='fichetarification',
            name='fichecontrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichecontrol'),
        ),
    ]
