# Generated by Django 4.2.4 on 2023-11-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0010_alter_stragietarification_application_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stragietarification',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
