# Generated by Django 4.2.4 on 2023-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0010_remove_factures_numero_facture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetarification',
            name='date_tarification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichetarification',
            name='observation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
