# Generated by Django 4.2.4 on 2023-12-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0010_rename_type_controllingot_type_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='observation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
