# Generated by Django 4.2.4 on 2023-11-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0009_rename_periode_rapactivites_periode2_and_more'),
        ('commercial', '0011_alter_fichetarification_date_tarification_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Fournisseur',
        ),
    ]
