# Generated by Django 4.2.4 on 2023-11-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0012_paiements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lingot',
            old_name='quantite_or_fin',
            new_name='or_fin',
        ),
        migrations.RenameField(
            model_name='lingot',
            old_name='titre_carat',
            new_name='titre',
        ),
    ]
