# Generated by Django 4.2.4 on 2023-12-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0012_control_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='numero_control',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
