# Generated by Django 4.2.4 on 2023-11-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0012_rename_client_fournisseur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeClient',
            new_name='TypeFournisseur',
        ),
    ]
