# Generated by Django 4.2.4 on 2023-11-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0013_rename_typeclient_typefournisseur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='type_client',
            new_name='type_fournisseur',
        ),
    ]
