# Generated by Django 4.2.4 on 2023-12-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0013_control_numero_control'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='controllingot',
            unique_together=set(),
        ),
    ]
