# Generated by Django 4.2.4 on 2023-11-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0013_rename_quantite_or_fin_lingot_or_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesee',
            name='quantite_or_fin',
        ),
        migrations.RemoveField(
            model_name='pesee',
            name='titre_carat',
        ),
    ]
