# Generated by Django 4.2.4 on 2023-11-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0014_rename_type_client_fournisseur_type_fournisseur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.AlterModelOptions(
            name='typefournisseur',
            options={'verbose_name_plural': 'Types fournisseurs'},
        ),
    ]
