# Generated by Django 4.2.4 on 2023-11-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0014_remove_pesee_quantite_or_fin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesee',
            old_name='valide',
            new_name='actif',
        ),
    ]
