# Generated by Django 4.2.4 on 2023-12-06 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0014_alter_controllingot_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllingot',
            name='lingot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.lingot'),
        ),
    ]
