# Generated by Django 4.2.4 on 2023-11-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0015_alter_fournisseur_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichecontrol',
            name='numero',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
