# Generated by Django 4.2.4 on 2023-12-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0016_alter_controllingot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pourcentagesubstancecontrollingot',
            name='poids_brut',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pourcentagesubstancecontrollingot',
            name='pourcentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
    ]
