# Generated by Django 4.2.4 on 2023-11-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0016_fichecontrol_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichecontrol',
            old_name='client',
            new_name='fournisseur',
        ),
        migrations.RenameField(
            model_name='fichetarification',
            old_name='client',
            new_name='fournisseur',
        ),
    ]
