# Generated by Django 4.2.4 on 2023-11-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0018_rename_typelingot_typesubstance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichetarification',
            name='fournisseur',
        ),
        migrations.AlterField(
            model_name='fichetarification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
