# Generated by Django 4.2.4 on 2023-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0018_rename_poids_brut_pourcentagesubstancecontrollingot_poids'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllingot',
            name='date_control',
            field=models.DateTimeField(null=True),
        ),
    ]
