# Generated by Django 4.2.4 on 2023-11-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0019_remove_fichetarification_fournisseur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lingot',
            old_name='client',
            new_name='fournisseur',
        ),
        migrations.RenameField(
            model_name='paiements',
            old_name='client',
            new_name='fournisseur',
        ),
        migrations.RenameField(
            model_name='stragietarification',
            old_name='type_client',
            new_name='type_fournisseur',
        ),
    ]
