# Generated by Django 4.2.4 on 2023-11-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0020_rename_client_lingot_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichetarification',
            name='numero',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
