# Generated by Django 4.2.4 on 2023-12-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0021_alter_prixdessubstances_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrixDesSubstancesFactureFactureDefinitive',
        ),
        migrations.CreateModel(
            name='PrixDesSubstancesFactureDefinitive',
            fields=[
            ],
            options={
                'verbose_name_plural': 'PRIX DES SUBSTANCES',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commercial.lingot',),
        ),
    ]
