# Generated by Django 4.2.4 on 2023-11-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0021_fichetarification_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetarification',
            name='fichecontrol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichecontrol'),
        ),
    ]
