# Generated by Django 4.2.4 on 2023-12-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0022_delete_prixdessubstancesfacturefacturedefinitive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='cours',
        ),
    ]
