# Generated by Django 4.2.4 on 2023-11-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0022_alter_fichetarification_fichecontrol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modepayement',
            options={'verbose_name_plural': 'Modes de payements'},
        ),
        migrations.AlterModelOptions(
            name='typesubstance',
            options={'verbose_name_plural': 'Types Substances'},
        ),
        migrations.AddField(
            model_name='modepayement',
            name='readonly',
            field=models.BooleanField(default=True),
        ),
    ]
