# Generated by Django 4.2.4 on 2023-11-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0023_alter_modepayement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modepayement',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
    ]
