# Generated by Django 4.2.4 on 2023-12-06 17:59

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0024_alter_facture_poids_selon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='fiche_tarification',
        ),
        migrations.RemoveField(
            model_name='rapportaffinage',
            name='user',
        ),
        migrations.CreateModel(
            name='FactureProforma',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Factures Proforma',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commercial.facture',),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='pays',
            field=django_countries.fields.CountryField(default='BF', max_length=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='pays',
            field=django_countries.fields.CountryField(default='BF', max_length=2),
        ),
        migrations.DeleteModel(
            name='FactureDefinitive',
        ),
        migrations.DeleteModel(
            name='Factures',
        ),
        migrations.DeleteModel(
            name='RapportAffinage',
        ),
        migrations.CreateModel(
            name='FactureDefinitive',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Factures Defintives',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commercial.facture',),
        ),
        migrations.CreateModel(
            name='RapportAffinage',
            fields=[
            ],
            options={
                'verbose_name_plural': "Rapports d'affinages",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commercial.control',),
        ),
    ]
