# Generated by Django 4.2.4 on 2023-11-08 19:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercial', '0024_alter_modepayement_readonly'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paiements',
            new_name='Payements',
        ),
    ]
