# Generated by Django 4.2.4 on 2023-12-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0025_remove_factures_fiche_tarification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='cours_du_dollar',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
