# Generated by Django 4.2.4 on 2023-11-08 19:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercial', '0025_rename_paiements_payements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payements',
            new_name='Payement',
        ),
        migrations.AlterModelOptions(
            name='payement',
            options={'verbose_name_plural': 'Payements'},
        ),
    ]
