# Generated by Django 4.2.4 on 2023-12-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0026_facture_cours_du_dollar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='type_control',
            new_name='type_de_control',
        ),
    ]
