# Generated by Django 4.2.4 on 2023-11-10 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('commercial', '0026_rename_payements_payement_alter_payement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payement',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payement',
            name='confirme',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payement',
            name='direction',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], default='ENTREE', max_length=6),
        ),
        migrations.AddField(
            model_name='payement',
            name='reference',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='media/attachments/commercial/')),
                ('description', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
