# Generated by Django 4.2.4 on 2023-12-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0027_rename_type_control_control_type_de_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='cours_du_dollar',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
