# Generated by Django 4.2.4 on 2023-12-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0028_alter_facture_cours_du_dollar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pourcentagesubstancecontrollingot',
            old_name='type_substance',
            new_name='type_de_substance',
        ),
        migrations.RenameField(
            model_name='prixdessubstances',
            old_name='substance',
            new_name='control_lingot',
        ),
        migrations.AlterUniqueTogether(
            name='prixdessubstances',
            unique_together={('facture', 'control_lingot')},
        ),
        migrations.AddField(
            model_name='prixdessubstances',
            name='type_de_substance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commercial.typesubstance'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pourcentagesubstancecontrollingot',
            unique_together={('lingot', 'type_de_substance')},
        ),
    ]
