# Generated by Django 4.2.4 on 2023-11-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0028_rename_payement_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferedFicheTarification',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commercial.fichetarification',),
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='fichetarification',
            name='transferer',
            field=models.BooleanField(default=False),
        ),
    ]
