# Generated by Django 4.2.4 on 2023-11-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0029_transferedfichetarification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferedFicheTarification',
        ),
        migrations.CreateModel(
            name='TransferedFicheTarification',
            fields=[
                ('fichetarification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commercial.fichetarification')),
            ],
            options={
                'verbose_name_plural': 'Paiements en attentes',
            },
            bases=('commercial.fichetarification',),
        ),
    ]
