# Generated by Django 4.2.4 on 2023-11-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0030_delete_transferedfichetarification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferedFicheTarification',
        ),
        migrations.CreateModel(
            name='TransferedFicheTarification',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Paiements en attentes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commercial.fichetarification',),
        ),
    ]
