# Generated by Django 4.2.4 on 2023-12-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0031_alter_prixdessubstances_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='prixdessubstances',
            name='cours_de_substance',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
