# Generated by Django 4.2.4 on 2023-12-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0032_prixdessubstances_cours_de_substance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prixdessubstances',
            name='cours_de_substance',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
    ]
