# Generated by Django 4.2.4 on 2023-11-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0032_fichetarification_cours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichetarification',
            name='transferer',
        ),
    ]
