# Generated by Django 4.2.4 on 2023-11-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0033_remove_fichetarification_transferer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetarification',
            name='fichecontrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichecontrol'),
        ),
    ]
