# Generated by Django 4.2.4 on 2023-12-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0033_alter_prixdessubstances_cours_de_substance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prixdessubstances',
            name='observation',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
