# Generated by Django 4.2.4 on 2023-11-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0034_alter_fichetarification_fichecontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichetarification',
            name='transferer',
            field=models.BooleanField(default=False),
        ),
    ]
