# Generated by Django 4.2.4 on 2023-11-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0035_fichetarification_transferer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetarification',
            name='date_tarification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
