# Generated by Django 4.2.4 on 2023-12-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0035_alter_prixdessubstances_poids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='societe',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
