# Generated by Django 4.2.4 on 2023-11-12 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercial', '0036_alter_fichetarification_date_tarification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('direction', models.CharField(choices=[('in', 'ENTREE'), ('out', 'SORTIE')], default='ENTREE', max_length=6)),
                ('description', models.TextField()),
                ('archived', models.BooleanField(default=False)),
                ('confirme', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('fiche_tarification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichetarification')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fournisseur')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
