# Generated by Django 4.2.4 on 2023-12-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0038_alter_client_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='cours_en_euro',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
