# Generated by Django 4.2.4 on 2023-11-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0038_rename_paiement_payement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payement',
            old_name='fiche_tarification',
            new_name='fichetarification',
        ),
    ]
