# Generated by Django 4.2.4 on 2023-11-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0039_rename_fiche_tarification_payement_fichetarification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payement',
            old_name='description',
            new_name='observation',
        ),
    ]
