# Generated by Django 4.2.4 on 2023-12-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0041_alter_facture_cours_en_euro'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='reduction_commercial',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='prixdessubstances',
            name='reduction_commercial',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
    ]
