# Generated by Django 4.2.4 on 2023-11-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0041_poyement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poyement',
        ),
    ]
