# Generated by Django 4.2.4 on 2023-12-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0042_facture_reduction_commercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prixdessubstances',
            name='reduction_commercial',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True),
        ),
    ]
