# Generated by Django 4.2.4 on 2023-11-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0042_delete_poyement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
