# Generated by Django 4.2.4 on 2023-11-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0043_alter_payement_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='piecejointe',
            field=models.FileField(null=True, unique=True, upload_to='uploads/commercial'),
        ),
    ]
