# Generated by Django 4.2.4 on 2023-12-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0043_alter_prixdessubstances_reduction_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='facture_signe',
            field=models.FileField(blank=True, null=True, upload_to='uploads/commercial/vente/facture'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='reduction_commercial',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='payement',
            name='autre_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/commercial/achat/autres'),
        ),
        migrations.AlterField(
            model_name='payement',
            name='document_identite',
            field=models.FileField(blank=True, null=True, upload_to='uploads/commercial/commercial/achat/doc_identites'),
        ),
        migrations.AlterField(
            model_name='payement',
            name='document_payement',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='uploads/commercial/achat/doc_payement'),
        ),
        migrations.AlterField(
            model_name='payement',
            name='recu_payement',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='uploads/commercial/commercial/achat/recu'),
        ),
        migrations.AlterField(
            model_name='piecejointe',
            name='file',
            field=models.FileField(upload_to='uploads/commercial/'),
        ),
        migrations.AlterField(
            model_name='prixdessubstances',
            name='reduction_commercial',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
    ]
