# Generated by Django 4.2.4 on 2023-11-13 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0044_payement_piecejointe'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
