# Generated by Django 4.2.4 on 2023-12-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0044_facture_facture_signe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controllingot',
            old_name='type_control',
            new_name='type_de_control',
        ),
    ]
