# Generated by Django 4.2.4 on 2023-11-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0045_payement_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='factures',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichecontrol',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichetarification',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fonte',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lingot',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mouvementlingot',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
