# Generated by Django 4.2.4 on 2023-12-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0045_rename_type_control_controllingot_type_de_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='document_signe',
            field=models.FileField(blank=True, null=True, upload_to='uploads/commercial/control/'),
        ),
    ]
