# Generated by Django 4.2.4 on 2023-11-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0046_factures_archived_fichecontrol_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lingot',
            name='densite',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
