# Generated by Django 4.2.4 on 2023-11-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0047_alter_lingot_densite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lingot',
            name='densite',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True),
        ),
    ]
