# Generated by Django 4.2.4 on 2023-12-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0047_alter_control_options_alter_control_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='poids_selon',
            field=models.CharField(choices=[('bumigeb', 'Control BUMIGEB'), ('affinage', 'Rapport affinage'), ('sonasp', 'Control SONASP')], default=None, max_length=20),
        ),
    ]
