# Generated by Django 4.2.4 on 2023-11-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0048_alter_lingot_densite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lingot',
            options={'ordering': ['created'], 'verbose_name_plural': 'Lingots'},
        ),
        migrations.AlterModelOptions(
            name='pesee',
            options={'ordering': ['created'], 'verbose_name_plural': 'Pesees'},
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
