# Generated by Django 4.2.4 on 2023-12-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0048_alter_facture_poids_selon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='controllingot',
            unique_together={('control', 'lingot')},
        ),
        migrations.AlterField(
            model_name='controllingot',
            name='lingot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.lingot'),
        ),
        migrations.AlterUniqueTogether(
            name='controllingot',
            unique_together={('control', 'lingot'), ('lingot', 'type_de_control')},
        ),
    ]
