# Generated by Django 4.2.4 on 2023-11-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0049_alter_lingot_options_alter_pesee_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='phone_number',
            new_name='telephone',
        ),
    ]
