# Generated by Django 4.2.4 on 2023-12-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0049_alter_controllingot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='observation',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
