# Generated by Django 4.2.4 on 2023-11-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0050_rename_phone_number_fournisseur_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fonte',
            old_name='date_fin',
            new_name='date_entree',
        ),
        migrations.RenameField(
            model_name='fonte',
            old_name='date_debut',
            new_name='date_sortie',
        ),
        migrations.AddField(
            model_name='lingot',
            name='is_fonte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='etat',
            field=models.CharField(choices=[('out', 'En cours'), ('in', 'Fondu')], max_length=10),
        ),
        migrations.CreateModel(
            name='LingotFondus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercial.fonte')),
                ('lingot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercial.lingot')),
            ],
        ),
    ]
