# Generated by Django 4.2.4 on 2023-11-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0051_rename_date_fin_fonte_date_entree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonte',
            name='date_entree',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='etat',
            field=models.CharField(choices=[('out', 'En cours'), ('in', 'Fondu')], default='out', max_length=10),
        ),
    ]
