# Generated by Django 4.2.4 on 2023-11-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0052_alter_fonte_date_entree_alter_fonte_date_sortie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fonte',
            old_name='date_entree',
            new_name='date_retour',
        ),
    ]
