# Generated by Django 4.2.4 on 2023-12-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0053_alter_pourcentagesubstancecontrollingot_pourcentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='type_de_facture',
            field=models.CharField(choices=[('proforma', 'Facture Proforma'), ('definitive', 'Facture definitive'), ('autre', 'Autre')], default='proforma', editable=False, max_length=20),
        ),
    ]
