# Generated by Django 4.2.4 on 2023-12-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0054_alter_facture_type_de_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='date',
        ),
    ]
