# Generated by Django 4.2.4 on 2023-11-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0054_lingotfondus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lingot',
            name='observation',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
