# Generated by Django 4.2.4 on 2023-12-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0055_remove_vente_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='vendre_selon',
            field=models.CharField(choices=[('bumigeb', 'Control BUMIGEB'), ('affinage', 'Rapport affinage'), ('sonasp', 'Control SONASP')], default='bumigeb', max_length=20),
        ),
    ]
