# Generated by Django 4.2.4 on 2023-11-18 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0055_alter_lingot_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonte',
            name='date_sortie',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
