# Generated by Django 4.2.4 on 2023-12-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0056_vente_vendre_selon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='control',
            unique_together=set(),
        ),
    ]
