# Generated by Django 4.2.4 on 2023-11-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0056_alter_fonte_date_sortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonte',
            name='fondu',
            field=models.BooleanField(default=False),
        ),
    ]
