# Generated by Django 4.2.4 on 2023-11-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0057_fonte_fondu'),
    ]

    operations = [
        migrations.AddField(
            model_name='lingot',
            name='numero',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
