# Generated by Django 4.2.4 on 2023-12-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0057_alter_control_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='vente',
        ),
    ]
