# Generated by Django 4.2.4 on 2023-12-09 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0058_remove_control_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.vente'),
        ),
    ]
