# Generated by Django 4.2.4 on 2023-11-19 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercial', '0059_remove_fonte_lingots_lingot_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonte',
            name='valider_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valider_par', to=settings.AUTH_USER_MODEL),
        ),
    ]
