# Generated by Django 4.2.4 on 2023-12-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0060_vente_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='poids_selon',
        ),
    ]
