# Generated by Django 4.2.4 on 2023-11-19 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercial', '0060_fonte_valider_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlBUMIGEB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateTimeField(auto_now_add=True)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('out', 'En cours'), ('in', '')], default='out', max_length=10)),
                ('observation', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('reintegrer_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reintegrer_par', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
