# Generated by Django 4.2.4 on 2023-11-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0061_controlbumigeb'),
    ]

    operations = [
        migrations.AddField(
            model_name='lingot',
            name='Control_BUMIGEB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.controlbumigeb'),
        ),
    ]
