# Generated by Django 4.2.4 on 2023-11-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0062_lingot_control_bumigeb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lingot',
            old_name='Control_BUMIGEB',
            new_name='control_bumigeb',
        ),
    ]
