# Generated by Django 4.2.4 on 2023-12-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0065_alter_fournisseur_cartartisan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structuredecontrol',
            options={'verbose_name_plural': 'Structures de control'},
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='cartartisan',
        ),
    ]
