# Generated by Django 4.2.4 on 2023-12-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0067_control_control_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_client',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
