# Generated by Django 4.2.4 on 2023-12-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0068_alter_control_control_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='control_client',
        ),
    ]
