# Generated by Django 4.2.4 on 2023-12-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0069_remove_control_control_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='control_client',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
