# Generated by Django 4.2.4 on 2023-12-10 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0071_control_date_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='societe',
            field=models.CharField(default=datetime.datetime(2023, 12, 10, 10, 57, 59, 38678, tzinfo=datetime.timezone.utc), max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(default=datetime.datetime(2023, 12, 10, 10, 58, 6, 974588, tzinfo=datetime.timezone.utc), max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='prenom',
            field=models.CharField(default=datetime.datetime(2023, 12, 10, 10, 58, 10, 526166, tzinfo=datetime.timezone.utc), max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structuredecontrol',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='structuredecontrol',
            name='societe',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
