# Generated by Django 4.2.4 on 2023-12-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0072_alter_client_email_alter_client_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='representantfournisseur',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='representantfournisseur',
            name='nom',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='representantfournisseur',
            name='prenom',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
    ]
