# Generated by Django 4.2.4 on 2023-12-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0073_alter_client_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representantfournisseur',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='structuredecontrol',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
