# Generated by Django 4.2.4 on 2023-12-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0075_client_autre_document_client_document_identite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='autre_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/commercial/fournisseur'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='document_identite',
            field=models.FileField(blank=True, null=True, upload_to='uploads/commercial/fournisseur/'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='reference_document_identite',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
