# Generated by Django 4.2.4 on 2023-12-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0076_fournisseur_autre_document_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeClient',
            new_name='TypeDeClient',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='type_client',
            new_name='type_de_client',
        ),
    ]
