# Generated by Django 4.2.4 on 2023-12-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0077_rename_typeclient_typedeclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lingot',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fournisseur'),
        ),
    ]
