# Generated by Django 4.2.4 on 2023-12-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0078_alter_lingot_fournisseur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='numero_control',
            new_name='numero_de_control',
        ),
    ]
