# Generated by Django 4.2.4 on 2023-12-10 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0080_alter_facture_cours_en_euro'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 14, 20, 42, 717460, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
