# Generated by Django 4.2.4 on 2023-12-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0081_facture_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prixdessubstances',
            old_name='type_de_prix',
            new_name='type_de_facture',
        ),
        migrations.AlterUniqueTogether(
            name='prixdessubstances',
            unique_together={('facture', 'type_de_substance', 'type_de_facture')},
        ),
        migrations.RemoveField(
            model_name='prixdessubstances',
            name='control_lingot',
        ),
    ]
