# Generated by Django 4.2.4 on 2023-12-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0082_rename_type_de_prix_prixdessubstances_type_de_facture_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prixdessubstances',
            unique_together={('facture', 'type_de_substance')},
        ),
    ]
