# Generated by Django 4.2.4 on 2023-12-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0085_alter_facture_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='cours_du_dollar',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
    ]
