# Generated by Django 4.2.4 on 2023-12-12 08:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0086_alter_facture_cours_du_dollar'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='pourcentage_tva',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='cours_du_dollar',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='cours_en_euro',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='reduction_commercial',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
