# Generated by Django 4.2.4 on 2023-12-12 08:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0087_facture_pourcentage_tva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='pourcentage_tva',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
