# Generated by Django 4.2.4 on 2023-12-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0089_alter_pourcentagesubstancelingot_pourcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetarification',
            name='date_tarification',
            field=models.DateTimeField(null=True),
        ),
    ]
