# Generated by Django 4.2.4 on 2023-12-13 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0090_alter_fichetarification_date_tarification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lingot',
            name='fichecontrol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichecontrol'),
        ),
    ]
