# Generated by Django 4.2.4 on 2023-12-13 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0091_alter_lingot_fichecontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetarification',
            name='fichecontrol',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.fichecontrol'),
        ),
    ]
