# Generated by Django 4.2.4 on 2023-12-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0092_alter_fichetarification_fichecontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichecontrol',
            name='document_signe',
            field=models.FileField(blank=True, null=True, upload_to='uploads/commercial/fichecontrol/'),
        ),
    ]
