# Generated by Django 4.2.4 on 2023-12-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0093_fichecontrol_document_signe'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichetarification',
            name='document_signe',
            field=models.FileField(blank=True, null=True, upload_to='uploads/commercial/fichecontrol/'),
        ),
    ]
