# Generated by Django 4.2.4 on 2023-12-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0094_fichetarification_document_signe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='document_identite',
            field=models.FileField(null=True, upload_to='uploads/commercial/commercial/achat/doc_identites'),
        ),
        migrations.AlterField(
            model_name='payement',
            name='document_payement',
            field=models.FileField(null=True, unique=True, upload_to='uploads/commercial/achat/doc_payement'),
        ),
        migrations.AlterField(
            model_name='payement',
            name='reference_document_identite',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='payement',
            name='reference_payement',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
