# Generated by Django 4.2.4 on 2023-12-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0095_alter_payement_document_identite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='document_payement',
            field=models.FileField(null=True, upload_to='uploads/commercial/achat/doc_payement'),
        ),
        migrations.AlterField(
            model_name='payement',
            name='recu_payement',
            field=models.FileField(blank=True, null=True, upload_to='uploads/commercial/commercial/achat/recu'),
        ),
    ]
