# Generated by Django 4.2.4 on 2023-12-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0096_alter_payement_document_payement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetarification',
            name='cours',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True),
        ),
    ]
