# Generated by Django 4.2.4 on 2023-12-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0097_alter_fichetarification_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSClient',
            fields=[
            ],
            options={
                'verbose_name_plural': 'SMS Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commercial.sms',),
        ),
        migrations.CreateModel(
            name='SMSFournisseur',
            fields=[
            ],
            options={
                'verbose_name_plural': 'SMS Fournisseurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commercial.sms',),
        ),
        migrations.AddField(
            model_name='sms',
            name='type_de_message',
            field=models.CharField(choices=[('f', 'fournisseur'), ('c', 'client')], default='f', max_length=20),
        ),
    ]
