# Generated by Django 4.2.4 on 2023-12-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0099_sms_non_envoye'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='non_envoye',
            new_name='list_non_envoye',
        ),
    ]
