# Generated by Django 4.2.4 on 2023-12-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0101_sms_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='sent',
            new_name='envoye',
        ),
    ]
